export { default as Home } from './Home'
export { default as Movies } from './Movies'
export { default as TvShows } from './TvShows'
export { default as MovieDetails } from './MovieDetails'
export { default as TvShowDetails } from './TvShowDetails'
export { default as NotFound } from './NotFound'